export const plans = [
  {
    id: 1,
    title: "Starter",
    priceM: 39,
    centsM: 99,
    priceY: 399,
    cpu: "4 vCPU",
    ram: "8GB RAM",
    storage: "50GB NVMe Storage",
  },
  {
    id: 2,
    title: "Pro",
    priceM: 59,
    centsM: 99,
    priceY: 599,
    cpu: "6 vCPU",
    ram: "12GB RAM",
    storage: "60GB NVMe Storage",
  },
  {
    id: 3,
    title: "Advanced",
    priceM: 79,
    centsM: 99,
    priceY: 799,
    cpu: "8 vCPU",
    ram: "16GB RAM",
    storage: "70GB NVMe Storage",
  },
  {
    id: 4,
    title: "Elite",
    priceM: 159,
    centsM: 99,
    priceY: 1599,
    cpu: "16 vCPU",
    ram: "32GB RAM",
    storage: "100GB NVMe Storage",
  },
];
